"""create verification jobs and api keys tables

Revision ID: 00554f8591a9
Revises: 
Create Date: 2026-05-13 15:09:17.191020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00554f8591a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Enum('active', 'revoked', name='key_status'), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('verification_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('VERIFIED', 'FAILED', 'PARTIAL', 'PROCESSING', name='verificationstatus'), nullable=False),
    sa.Column('document_type', sa.Enum('PAN', 'GST_CERTIFICATE', 'AADHAR', name='documenttype'), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('api_key_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_jobs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
